config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'

  resource :rsvp
  resources :reports
  get 'welcome/index'

  root 'welcome#index'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  extend FriendlyId
  friendly_id :registration_code, use: :slugged

  validates :email, presence: true
  validates :name, presence: true

  def registration_code=(value)
    attribute_will_change!('registration_code') if registration_code != value
    @registration_code = value
  end

  def registration_code
    if @registration_code.present?
      @registration_code
    else
      @registration_code = generate_registration_code
      attribute_will_change!('registration_code')
    end
  end

  def generate_registration_code
    SecureRandom.hex(2)
  end

  def registration_code_changed?
    changed.include?('registration_code')
  end

  def should_generate_new_friendly_id?
    slug.nil? || registration_code_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_rsvp=(rsvp)
    session[:registration_code] = rsvp.slug
  end

  def base_url
    root_url
  end
  helper_method :base_url

  def current_rsvp
    Rsvp.friendly.find(session[:registration_code])
  rescue ActiveRecord::RecordNotFound
  end
  helper_method :current_rsvp
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @rsvps = Rsvp.all
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp#, only: [:show, :edit, :update, :destroy]

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
    render layout: 'welcome'
  end

  # GET /rsvps/new
  def new
    if @rsvp.present?
      redirect_to edit_rsvp_path(@rsvp)
    else
      @rsvp = Rsvp.new
    end
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)
    respond_to do |format|
      if @rsvp.save
        self.current_rsvp = @rsvp
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = current_rsvp
    rescue ActiveRecord::RecordNotFound
    end

    def base_url
      rsvp_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.require(:rsvp).permit(:email, :name, :coming, :overnight, :additional_guest, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to rsvp_path if current_rsvp
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: 'collapse', target: '#navbar' }}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'William & Geraldine', base_url, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Details', base_url + '#details'
        %li= link_to 'Gift Registry', base_url + '#registry'
        %li= link_to 'Map', base_url + '#map'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ "http-equiv"=>"X-UA-Compatible", content: "IE=edge" }
    %meta{ name:"viewport", content:"width=device-width, initial-scale=1" }
    %title William & Geraldine Wedding
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.cover-background
    = render 'layouts/header'
    .cover-overlay
      .container
        = yield

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ "http-equiv"=>"X-UA-Compatible", content: "IE=edge" }
    %meta{ name:"viewport", content:"width=device-width, initial-scale=1" }
    %title William & Geraldine Wedding
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'

    = yield

app/views/reports/index.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title RSVPs
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th Coming?
        %th Guests
        %th Message
    %tbody
      - @rsvps.each do |rsvp|
        %tr
          %td
            = rsvp.name
          %td= rsvp.email
          %td= rsvp.coming ? 'Yes' : 'No'
          %td= rsvp.additional_guest
          %td= rsvp.message

app/views/rsvps/_form.html.haml
= simple_form_for(@rsvp, url: rsvp_path) do |f|
  = f.error_notification
  .form-inputs
    = f.input :email
    = f.input :name
    = f.input :coming, inline_label: 'Will you be attending the wedding?'
    = f.input :overnight, inline_label: 'Will you be staying at the resort during your visit?'
    = f.input :additional_guest, label: 'Are you bringing anyone with you?'
    = f.input :message, label: 'Got any special messages for us?', input_html: { rows: 10 }
  .form-actions.text-right
    = f.button :submit, 'Submit RSVP', class: 'btn btn-primary'

app/views/rsvps/_invitation.html.haml
%h1 You are invited
%h2 To the wedding of William Fisher & Geraldine Miller
%h3 October 10th, 2016 - Chena Hot Springs - Fairbanks, Alaska

%br/
- if current_rsvp.present?
  = link_to 'Update RSVP?', edit_rsvp_path, class: 'btn btn-default btn-lg'
- else
  = link_to 'RSVP', new_rsvp_path, class: 'btn btn-default btn-lg'

app/views/rsvps/_registry.html.haml
#registry.registry
  %h2 Gift Registry

  = link_to 'https://www.amazon.com/wedding/geraldine-miller-william-fisher-chena-hot-springs-october-2016/registry/2UYOPEP6OGCBY' do
    = image_tag 'amazon.png'

app/views/rsvps/_rsvp.html.haml
%dl.dl-horizontal.rsvp.thumbnail.text-left.hidden-sm.hidden-xs{ style: '' }
  %dt Name
  %dd= @rsvp.name
  %dt Email
  %dd= @rsvp.email
  %dt Attending?
  %dd= @rsvp.coming? ? 'Yes' : 'No'
  %dt Overnight?
  %dd= @rsvp.overnight? ? 'Yes' : 'No'
  - unless @rsvp.additional_guest.blank?
    %dt Guest?
    %dd= @rsvp.additional_guest
  - unless @rsvp.message.blank?
    %dt Message
    %dd
      :markdown
        #{@rsvp.message}

app/views/rsvps/_thanks.html.haml
.text-center
  %h1
    Thank you!
  %h2 Your RSVP response has been saved

  - if @rsvp.coming?
    %p We're looking forward to seeing you there


  %br/
  = link_to 'Update RSVP', edit_rsvp_path, class: 'btn btn-default'

  = render @rsvp

app/views/rsvps/_venue.html.haml
%h2 Date & Venue:
%p
  Oct. 10th, 2016 - 10:00am
  %br/
  Chena Hot Springs Resort
  (#{link_to 'map', root_url + '#map'})
  %br/
  The Chena Room
%p
  Send questions or messages to #{mail_to 'will+wedding@teknofire.net'}

app/views/rsvps/edit.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title RSVP
  .panel-body
    = render 'form'

app/views/rsvps/new.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title RSVP
  .panel-body
    = render 'form'

app/views/rsvps/show.html.haml
#intro.introduction{ class: current_rsvp.present? ? 'thanks' : '' }
  .cover
    .container.text
      - if current_rsvp.present?
        = render 'thanks'
      - else
        = render 'invitation'

#details.wedding-details
  .cover
    .container
      = render 'venue'

      %h2 Resort Activities
      %P
        After the wedding and brunch please feel free to enjoy the hot springs or other resort activities.
      .text-center
        %ul.nav
          %li= link_to 'Summer', 'http://www.chenahotsprings.com/summer-activities/'
          %li= link_to 'Winter', 'http://www.chenahotsprings.com/winter-activities/'

      = render 'registry'
%iframe#map{ src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1395.600041939964!2d-146.05917789344707!3d65.05297430049441!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5133d8acb8f60ccb%3A0x3b69840ff86f3f06!2sChena+Hot+Springs+Resort!5e0!3m2!1sen!2sus!4v1466890871019", frameborder:0, style: "border:0; width: 100%; height: 600px;",  allowfullscreen: true }

app/views/welcome/index.html.haml
#intro.introduction
  .cover
    .container.text
      %h1 We're getting married
      %h2 William Fisher & Geraldine Miller
      %h3 October 10th, 2016 - Chena Hot Springs - Fairbanks, Alaska

#details.wedding-details
  .cover
    .container
      = render 'rsvps/venue'

      = render 'rsvps/registry'

%iframe#map{ src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1395.600041939964!2d-146.05917789344707!3d65.05297430049441!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5133d8acb8f60ccb%3A0x3b69840ff86f3f06!2sChena+Hot+Springs+Resort!5e0!3m2!1sen!2sus!4v1466890871019", frameborder:0, style: "border:0; width: 100%; height: 600px;",  allowfullscreen: true }